# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pummit < Formula
  desc ""
  homepage ""
  version "1.2.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.3/pummit_1.2.3_darwin_arm64.tar.gz"
      sha256 "8f9260df23c68feeb3cd58abdbc5a2c282dd20ed4e73d375903eca88ef4b7121"

      def install
        bin.install "pummit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.3/pummit_1.2.3_darwin_amd64.tar.gz"
      sha256 "11c17aacb218940af85dd903f7a551e3e4aeedc782136bfe1012bea90e5bbe90"

      def install
        bin.install "pummit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.3/pummit_1.2.3_linux_amd64.tar.gz"
      sha256 "6ec03f23a36cd99b7a6e2c5f58d99d93b7db353d327c5b79212f9f9e543673a7"

      def install
        bin.install "pummit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.3/pummit_1.2.3_linux_armv6.tar.gz"
      sha256 "35bd55ca4035de2fa7f46604f5fa659e4828b8868cba31026f8d4d18c9cde981"

      def install
        bin.install "pummit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.3/pummit_1.2.3_linux_arm64.tar.gz"
      sha256 "298674cbf6dc15f625646c4e8d4588e91abb8b61b486b977f121ff5b7ae74e51"

      def install
        bin.install "pummit"
      end
    end
  end
end
