# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pummit < Formula
  desc ""
  homepage ""
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.2/pummit_1.2.2_darwin_amd64.tar.gz"
      sha256 "f240604ee2ea2acef3b9eabab9020f5cd360db43df684ea0d9a2dbd10abea9f2"

      def install
        bin.install "pummit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.2/pummit_1.2.2_darwin_arm64.tar.gz"
      sha256 "668ae9fe914bf36e1f5728b9bb4e6a51becba8a6d3ee861d77fd6d36003b61e4"

      def install
        bin.install "pummit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.2/pummit_1.2.2_linux_armv6.tar.gz"
      sha256 "48ae2cc874922d5e316e747911438ec662fa2f3725d1e3577f604ba904a470c7"

      def install
        bin.install "pummit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.2/pummit_1.2.2_linux_amd64.tar.gz"
      sha256 "ff1769071baf638b87302d998f3a62c106a25c3c3b26708d4641303f2f5bb653"

      def install
        bin.install "pummit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.2/pummit_1.2.2_linux_arm64.tar.gz"
      sha256 "40adf76949f64358b486e20e03f9e428e8aae3a5714d345e145d11eaffb53adf"

      def install
        bin.install "pummit"
      end
    end
  end
end
