# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pummit < Formula
  desc ""
  homepage ""
  version "1.2.4"

  on_macos do
    on_intel do
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.4/pummit_1.2.4_darwin_amd64.tar.gz"
      sha256 "c68bbd8ab235008181ae7711e6c9573fab27b18bfe74cd6bd0766ab3818a3114"

      def install
        bin.install "pummit"
      end
    end
    on_arm do
      url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.4/pummit_1.2.4_darwin_arm64.tar.gz"
      sha256 "eed4485ac0c54b2c3481700c29a7636b171fe644e16ad7831ecff49bcb337646"

      def install
        bin.install "pummit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.4/pummit_1.2.4_linux_amd64.tar.gz"
        sha256 "e6d98b0e52de56a8e4e977ab84b92b659a72034dff7e336debd4c2a11727cb86"

        def install
          bin.install "pummit"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.4/pummit_1.2.4_linux_armv6.tar.gz"
        sha256 "7896672b7ae9e2dab264be9e421575ce620d4116b07c4d5601df35ebe388ab44"

        def install
          bin.install "pummit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/HidemaruOwO/pummit/releases/download/v1.2.4/pummit_1.2.4_linux_arm64.tar.gz"
        sha256 "03094c9890ff913e1c26244c03f883411f5c858db02aa363c760c39163b40b4e"

        def install
          bin.install "pummit"
        end
      end
    end
  end
end
