# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VirtualSlimeAPI < Formula
  desc ""
  homepage ""
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.5/VirtualSlime-API_0.1.5_darwin_arm64.tar.gz"
      sha256 "91d570255e5759b7ea25bc7d5c018e7bb2192491e8d1031c9998c1d331953382"

      def install
        bin.install "VirtualSlime-API"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.5/VirtualSlime-API_0.1.5_darwin_amd64.tar.gz"
      sha256 "fab6814df99cf34f134bf4ff0d208b7c9ba5606877809e88e967bc5ccfecfaa5"

      def install
        bin.install "VirtualSlime-API"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.5/VirtualSlime-API_0.1.5_linux_amd64.tar.gz"
      sha256 "02cf4d40ba7eedd0ed0c99cca657eca3435c5448ddf4872b9898b0ab6e5642e8"

      def install
        bin.install "VirtualSlime-API"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.5/VirtualSlime-API_0.1.5_linux_armv6.tar.gz"
      sha256 "0636e4f50a9f34aaa01fdabf09ea0cd0f788b62832ed95be16efc4e537b57101"

      def install
        bin.install "VirtualSlime-API"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.5/VirtualSlime-API_0.1.5_linux_arm64.tar.gz"
      sha256 "705ec592a74ad2517518a63ede6ee265b7b3688a6f8582274981a1bc5288cfe0"

      def install
        bin.install "VirtualSlime-API"
      end
    end
  end
end
