# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VirtualslimeApi < Formula
  desc ""
  homepage ""
  version "0.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.6/VirtualSlime-API_0.1.6_darwin_arm64.tar.gz"
      sha256 "08168a338a91c7b103dd2852ef41f901551dd6a387750014b179228463fcfb40"

      def install
        bin.install "VirtualSlime-API"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.6/VirtualSlime-API_0.1.6_darwin_amd64.tar.gz"
      sha256 "c8fef0776530190a69fb43ad8e0b283fa0beb06d215cf2bfdcd324151c02fda1"

      def install
        bin.install "VirtualSlime-API"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.6/VirtualSlime-API_0.1.6_linux_amd64.tar.gz"
      sha256 "a5ff05dda2191e1946b375841118237ddea7d37c39067d80c40ca4d3d422ed5c"

      def install
        bin.install "VirtualSlime-API"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.6/VirtualSlime-API_0.1.6_linux_armv6.tar.gz"
      sha256 "b1b179d7a1b6a7552462febced77d63c0edb0585c615399dcfff7f5dace16b29"

      def install
        bin.install "VirtualSlime-API"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HidemaruOwO/VirtualSlime-API/releases/download/v0.1.6/VirtualSlime-API_0.1.6_linux_arm64.tar.gz"
      sha256 "e240b465f589f6084bf4bcbdc4d6bda82f84d3cd60c145701ad30831ed13f950"

      def install
        bin.install "VirtualSlime-API"
      end
    end
  end
end
